
def billie_jean(length, kick, snare, hihat_closed):
    length = int(length)
    b = int(length/16)
    kick.set_hit(8 * b, velocity=100)
    kick.set_hit(8 * b, velocity=90)
    for _ in range(2):
        snare.set_rest(4 * b)
        snare.set_hit(4 * b)
    hihat_closed.set_hits(length, 8)


def funky_drummer(length, kick, snare, hihat_closed, hihat_open):
    length = int(length)
    b = int(length/16)
    kick.set_hit(2 * b, velocity=100)
    kick.set_hit(4 * b, velocity=90)
    kick.set_hit(4 * b, velocity=90)
    kick.set_hit(3 * b, velocity=90)
    kick.set_hit(3 * b, velocity=90)
    snare.set_rest(4 * b)
    snare.set_hit(3 * b)
    snare.set_hit(2 * b)
    snare.set_hit(2 * b)
    snare.set_hit(1 * b)
    snare.set_hit(3 * b)
    snare.set_hit(1 * b)
    hihat_closed.set_hits(7 * b, 7)
    hihat_closed.set_rest(1 * b)
    hihat_closed.set_hits(5 * b, 5)
    hihat_closed.set_rest(1 * b)
    hihat_closed.set_hits(2 * b, 2)
    hihat_open.set_rest(7 * b)
    hihat_open.set_hit(6 * b)
    hihat_open.set_hit(3 * b)
    

def jungle(length, kick, snare, hihat_closed, hihat_open):
    length = int(length)
    b = int(length/32)
    hihat_open.set_hit(length, velocity=90)
    kick.set_hit(2 * b, velocity=90)
    kick.set_hit(8 * b, velocity=70)
    kick.set_hit(7 * b, velocity=90)
    kick.set_hit(1 * b, velocity=70)
    kick.set_hit(8 * b, velocity=70)
    kick.set_hit(6 * b, velocity=70)
    hihat_closed.set_hits(length, 16)
    snare.set_rest(4 * b)
    snare.set_hit(3 * b, velocity=90)
    snare.set_hit(2 * b, velocity=60)
    snare.set_hit(5 * b, velocity=60)
    snare.set_hit(3 * b, velocity=90)
    snare.set_hit(3 * b, velocity=60)
    snare.set_hit(3 * b, velocity=60)
    snare.set_hit(2 * b, velocity=60)
    snare.set_hit(5 * b, velocity=60)
    snare.set_hit(2 * b, velocity=60)

